spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security-db
    driver-class-name: org.postgresql.Driver
    username: secure-user
    password: 5771199m
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        enable_lazy_load_no_trans: true